name: wakatime-stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 1am UTC from Monday through Friday
    - cron: '5 1 * * 1-5'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "docs: updated stats"
          COMMIT_USERNAME: "vikimark"
          COMMIT_EMAIL: "mark.phurit@gmail.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TIMEZONE: "False"